import 'models.dart';

const kAlgebraRootId = 'linear_eq';

/// Algebra tree: elementary word problems through junior-high forms.
final algebraGraph = KnowledgeGraph(
  area: KnowledgeArea.algebra,
  rootId: kAlgebraRootId,
  nodes: const [
    KnowledgeNode(
      id: 'linear_eq',
      title: '一元一次方程',
      subtitle: r'$ax+b=c$',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sum_diff',
      title: '和差问题',
      subtitle: '和差求两数',
      level: KnowledgeLevel.l1,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'excess_deficit',
      title: '盈亏问题',
      subtitle: '分多与分少',
      level: KnowledgeLevel.l1,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'chicken_rabbit',
      title: '鸡兔同笼',
      subtitle: '头脚列方程',
      level: KnowledgeLevel.l1,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'ratio_share',
      title: '按份分配',
      subtitle: '比例与份数',
      level: KnowledgeLevel.l2,
      prerequisites: ['sum_diff'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'travel',
      title: '行程问题',
      subtitle: '相遇与追及',
      level: KnowledgeLevel.l2,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'work_rate',
      title: '工程问题',
      subtitle: '合作完工',
      level: KnowledgeLevel.l2,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'tree_plant',
      title: '植树问题',
      subtitle: '直线与封闭',
      level: KnowledgeLevel.l2,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'expand_dist',
      title: '分配律',
      subtitle: r'$(a+b)c$',
      level: KnowledgeLevel.l3,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'linear_ineq',
      title: '一元不等式',
      subtitle: r'$ax+b<c$',
      level: KnowledgeLevel.l3,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'arith_seq',
      title: '等差数列',
      subtitle: r'$a_n$ 与 $S_n$',
      level: KnowledgeLevel.l3,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'age_problem',
      title: '年龄问题',
      subtitle: '若干年后倍数',
      level: KnowledgeLevel.l3,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'square_form',
      title: '方阵问题',
      subtitle: '最外圈人数',
      level: KnowledgeLevel.l3,
      prerequisites: ['expand_dist'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'percent_mix',
      title: '浓度配比',
      subtitle: '百分数混合',
      level: KnowledgeLevel.l4,
      prerequisites: ['ratio_share'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'quadratic',
      title: '一元二次',
      subtitle: r'$ax^2+bx+c=0$',
      level: KnowledgeLevel.l4,
      prerequisites: ['linear_eq', 'expand_dist'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'grass_cow',
      title: '牛吃草',
      subtitle: '匀速生长',
      level: KnowledgeLevel.l4,
      prerequisites: ['work_rate'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'function_intro',
      title: '一次函数',
      subtitle: r'$y=kx+b$',
      level: KnowledgeLevel.l5,
      prerequisites: ['linear_eq', 'linear_ineq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'factor_poly',
      title: '因式分解',
      subtitle: '提公因式与公式',
      level: KnowledgeLevel.l5,
      prerequisites: ['expand_dist'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'am_gm',
      title: '均值不等式',
      subtitle: r'$a+b\ge 2\sqrt{ab}$',
      level: KnowledgeLevel.l6,
      prerequisites: ['linear_ineq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'stream_boat',
      title: '流水行船',
      subtitle: '顺水与逆水',
      level: KnowledgeLevel.l2,
      prerequisites: ['travel'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'train_bridge',
      title: '火车过桥',
      subtitle: '车长加桥长',
      level: KnowledgeLevel.l2,
      prerequisites: ['travel'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'geo_seq',
      title: '等比数列',
      subtitle: r'$a_n=a_1 q^{n-1}$',
      level: KnowledgeLevel.l3,
      prerequisites: ['arith_seq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'track_loop',
      title: '环形跑道',
      subtitle: '相对速度',
      level: KnowledgeLevel.l4,
      prerequisites: ['travel'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'percent_app',
      title: '折扣利润',
      subtitle: '百分数应用',
      level: KnowledgeLevel.l4,
      prerequisites: ['percent_mix'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'linear_sys',
      title: '二元一次方程',
      subtitle: r'$ax+by=c$',
      level: KnowledgeLevel.l5,
      prerequisites: ['linear_eq', 'sum_diff'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'direct_prop',
      title: '正比例',
      subtitle: r'$y=kx$',
      level: KnowledgeLevel.l2,
      prerequisites: ['ratio_share'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'inverse_prop',
      title: '反比例',
      subtitle: r'$xy=k$',
      level: KnowledgeLevel.l3,
      prerequisites: ['ratio_share'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'interest',
      title: '单利',
      subtitle: r'$I=prt$',
      level: KnowledgeLevel.l3,
      prerequisites: ['ratio_share'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'piecewise',
      title: '分段计费',
      subtitle: '起步价与续价',
      level: KnowledgeLevel.l4,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'ineq_sys',
      title: '不等式组',
      subtitle: '取交集',
      level: KnowledgeLevel.l4,
      prerequisites: ['linear_ineq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'compound',
      title: '复利',
      subtitle: '利生利',
      level: KnowledgeLevel.l5,
      prerequisites: ['interest'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'ratio_chain',
      title: '连比',
      subtitle: r'$a:b:c$',
      level: KnowledgeLevel.l3,
      prerequisites: ['ratio_share'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'rem_word',
      title: '余数应用',
      subtitle: '除余定解',
      level: KnowledgeLevel.l3,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'abs_eq',
      title: '绝对值',
      subtitle: r'$|x-a|=b$',
      level: KnowledgeLevel.l4,
      prerequisites: ['linear_eq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'quad_fn',
      title: '二次函数',
      subtitle: r'顶点与对称轴',
      level: KnowledgeLevel.l5,
      prerequisites: ['quadratic', 'function_intro'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'disc_val',
      title: '判别式',
      subtitle: r'$\Delta=b^2-4ac$',
      level: KnowledgeLevel.l5,
      prerequisites: ['quadratic'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'lin_zero',
      title: '一次截距',
      subtitle: r'$kx+b=0$',
      level: KnowledgeLevel.l4,
      prerequisites: ['function_intro'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'inv_graph',
      title: '反比例函数',
      subtitle: r'$y=k/x$',
      level: KnowledgeLevel.l4,
      prerequisites: ['inverse_prop', 'function_intro'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'axis_int',
      title: '抛物线截距',
      subtitle: '与坐标轴交点',
      level: KnowledgeLevel.l5,
      prerequisites: ['quad_fn'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'quad_ext',
      title: '二次最值',
      subtitle: '顶点纵坐标',
      level: KnowledgeLevel.l5,
      prerequisites: ['quad_fn'],
      practiceReady: true,
    ),
  ],
);
