import 'models.dart';

const kCalculationRootId = 'calc_addsub';

/// Calculation tree: mental arithmetic through fractions and new operations.
final calculationGraph = KnowledgeGraph(
  area: KnowledgeArea.calculation,
  rootId: kCalculationRootId,
  nodes: const [
    KnowledgeNode(
      id: 'calc_addsub',
      title: '加减巧算',
      subtitle: '凑整与拆分',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'calc_mul',
      title: '乘法巧算',
      subtitle: r'$25\times 16$',
      level: KnowledgeLevel.l1,
      prerequisites: ['calc_addsub'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'calc_laws',
      title: '运算律',
      subtitle: '交换结合分配',
      level: KnowledgeLevel.l1,
      prerequisites: ['calc_addsub'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'frac_ops',
      title: '分数四则',
      subtitle: r'通分与约分',
      level: KnowledgeLevel.l2,
      prerequisites: ['calc_addsub'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'frac_cmp',
      title: '分数比较',
      subtitle: '通分比大小',
      level: KnowledgeLevel.l2,
      prerequisites: ['frac_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'dec_rep',
      title: '循环小数',
      subtitle: r'$0.\dot{a}=a/9$',
      level: KnowledgeLevel.l2,
      prerequisites: ['frac_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'new_op',
      title: '新定义运算',
      subtitle: r'$a\oplus b=a+b+ab$',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_laws'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'split_unit',
      title: '裂项',
      subtitle: r'$1/n-1/(n+1)$',
      level: KnowledgeLevel.l3,
      prerequisites: ['frac_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'mean_avg',
      title: '平均数',
      subtitle: '总和与个数',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_addsub'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'page_num',
      title: '页码计数',
      subtitle: '编页用了几位',
      level: KnowledgeLevel.l4,
      prerequisites: ['mean_avg'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'complex_frac',
      title: '繁分数',
      subtitle: '分子分母都是分数',
      level: KnowledgeLevel.l4,
      prerequisites: ['frac_ops', 'split_unit'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'frac_of',
      title: '分数应用',
      subtitle: '求一个数的几分之几',
      level: KnowledgeLevel.l5,
      prerequisites: ['frac_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'gauss_sum',
      title: '连续自然数',
      subtitle: r'$1+2+\cdots+n$',
      level: KnowledgeLevel.l5,
      prerequisites: ['mean_avg'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'est_round',
      title: '估算',
      subtitle: '整十整百',
      level: KnowledgeLevel.l5,
      prerequisites: ['calc_addsub', 'calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'pow_value',
      title: '乘方',
      subtitle: r'$a^n$',
      level: KnowledgeLevel.l6,
      prerequisites: ['calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'odd_square_sum',
      title: '奇数求和',
      subtitle: r'$1+3+\cdots=n^2$',
      level: KnowledgeLevel.l6,
      prerequisites: ['gauss_sum'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'dec_arith',
      title: '小数四则',
      subtitle: '化成整数再算',
      level: KnowledgeLevel.l2,
      prerequisites: ['frac_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sq_diff',
      title: '平方差',
      subtitle: r'$(a+b)(a-b)$',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'complete_sq',
      title: '完全平方展开',
      subtitle: r'$(a\pm b)^2$',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'weighted_avg',
      title: '加权平均',
      subtitle: '份数不同的平均',
      level: KnowledgeLevel.l4,
      prerequisites: ['mean_avg'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'period_sum',
      title: '周期求和',
      subtitle: '循环节乘段数',
      level: KnowledgeLevel.l5,
      prerequisites: ['gauss_sum'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'square_sum',
      title: '平方求和',
      subtitle: r'$1^2+\cdots+n^2$',
      level: KnowledgeLevel.l6,
      prerequisites: ['odd_square_sum'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'scale_unit',
      title: '单位换算',
      subtitle: '千米与小时',
      level: KnowledgeLevel.l2,
      prerequisites: ['calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'unit_frac',
      title: '单位分数',
      subtitle: r'$1/n=1/(n+1)+\cdots$',
      level: KnowledgeLevel.l3,
      prerequisites: ['frac_ops', 'split_unit'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'grid_fill',
      title: '数表填空',
      subtitle: '行和列和',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_addsub'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'magic_sq',
      title: '幻方',
      subtitle: r'幻和 $n(n^{2}+1)/2$',
      level: KnowledgeLevel.l4,
      prerequisites: ['grid_fill'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'digit_swap',
      title: '数字对调',
      subtitle: r'$ab$ 与 $ba$',
      level: KnowledgeLevel.l4,
      prerequisites: ['calc_addsub', 'calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'avg_speed',
      title: '往返均速',
      subtitle: '调和平均',
      level: KnowledgeLevel.l5,
      prerequisites: ['weighted_avg'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'move_point',
      title: '小数点移动',
      subtitle: r'$\times 10^k$',
      level: KnowledgeLevel.l2,
      prerequisites: ['dec_arith'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cross_sum',
      title: '十字数阵',
      subtitle: '中心与四臂',
      level: KnowledgeLevel.l4,
      prerequisites: ['grid_fill'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sci_shift',
      title: '乘十的幂',
      subtitle: r'$a\times 10^n$',
      level: KnowledgeLevel.l3,
      prerequisites: ['calc_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cube_sum',
      title: '立方求和',
      subtitle: r'$1^3+\cdots+n^3$',
      level: KnowledgeLevel.l6,
      prerequisites: ['square_sum', 'gauss_sum'],
      practiceReady: true,
    ),
  ],
);
