import 'models.dart';

const kCombinatoricsRootId = 'count_add';

/// Combinatorics tree: counting through recurrence, graphs, and double counting.
final combinatoricsGraph = KnowledgeGraph(
  area: KnowledgeArea.combinatorics,
  rootId: kCombinatoricsRootId,
  nodes: const [
    KnowledgeNode(
      id: 'count_add',
      title: '加法原理',
      subtitle: '分类相加',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'count_mul',
      title: '乘法原理',
      subtitle: '分步相乘',
      level: KnowledgeLevel.l1,
      prerequisites: ['count_add'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'count_complement',
      title: '间接计数',
      subtitle: '总数减反面',
      level: KnowledgeLevel.l1,
      prerequisites: ['count_add', 'count_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'permutation',
      title: '排列',
      subtitle: r'$A_n^k$',
      level: KnowledgeLevel.l2,
      prerequisites: ['count_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'combination',
      title: '组合',
      subtitle: r'$C_n^k$',
      level: KnowledgeLevel.l2,
      prerequisites: ['permutation'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'factorial_count',
      title: '阶乘',
      subtitle: r'$n!$ 与全排列',
      level: KnowledgeLevel.l2,
      prerequisites: ['count_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'lattice_path',
      title: '格点路径',
      subtitle: '只向右向上',
      level: KnowledgeLevel.l3,
      prerequisites: ['combination'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'inclusion',
      title: '容斥入门',
      subtitle: r'$|A \cup B|$',
      level: KnowledgeLevel.l3,
      prerequisites: ['count_add', 'count_complement'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'binom_identity',
      title: '组合恒等式',
      subtitle: '对称与杨辉',
      level: KnowledgeLevel.l3,
      prerequisites: ['combination'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'pigeonhole',
      title: '抽屉原理',
      subtitle: '又名鸽笼',
      level: KnowledgeLevel.l4,
      prerequisites: ['count_add'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'coloring',
      title: '染色计数',
      subtitle: '分类与对称',
      level: KnowledgeLevel.l4,
      prerequisites: ['combination', 'pigeonhole'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'recurrence',
      title: '递推计数',
      subtitle: '状态转移',
      level: KnowledgeLevel.l5,
      prerequisites: ['lattice_path', 'factorial_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'graph_basic',
      title: '图论起步',
      subtitle: '度与路径',
      level: KnowledgeLevel.l5,
      prerequisites: ['pigeonhole'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'double_count',
      title: '双向计数',
      subtitle: '对应与放缩',
      level: KnowledgeLevel.l6,
      prerequisites: ['binom_identity', 'inclusion'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'circle_perm',
      title: '圆形排列',
      subtitle: r'$(n-1)!$',
      level: KnowledgeLevel.l2,
      prerequisites: ['factorial_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'repeat_perm',
      title: '重复排列',
      subtitle: r'$n!/k!$',
      level: KnowledgeLevel.l3,
      prerequisites: ['permutation'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'stars_bars',
      title: '隔板法',
      subtitle: '相同物品分堆',
      level: KnowledgeLevel.l4,
      prerequisites: ['combination'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'incl3',
      title: '三集合容斥',
      subtitle: r'$|A\cup B\cup C|$',
      level: KnowledgeLevel.l4,
      prerequisites: ['inclusion'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'derange',
      title: '错排',
      subtitle: '全不在原位',
      level: KnowledgeLevel.l5,
      prerequisites: ['factorial_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'adjacent_ban',
      title: '不相邻',
      subtitle: '插空与捆绑',
      level: KnowledgeLevel.l3,
      prerequisites: ['combination', 'permutation'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'group_split',
      title: '平均分组',
      subtitle: '无标号分堆',
      level: KnowledgeLevel.l3,
      prerequisites: ['combination'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'binom_row',
      title: '杨辉行和',
      subtitle: r'$2^n$',
      level: KnowledgeLevel.l3,
      prerequisites: ['binom_identity'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'board_color',
      title: '棋盘染色',
      subtitle: '黑白格',
      level: KnowledgeLevel.l4,
      prerequisites: ['coloring'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'adj_color',
      title: '相邻异色',
      subtitle: r'$k(k-1)^{n-1}$',
      level: KnowledgeLevel.l5,
      prerequisites: ['coloring'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'catalan',
      title: '卡特兰',
      subtitle: '括号与剖分',
      level: KnowledgeLevel.l6,
      prerequisites: ['combination', 'lattice_path'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'int_part',
      title: '整数分拆',
      subtitle: '不分顺序',
      level: KnowledgeLevel.l4,
      prerequisites: ['stars_bars'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'lattice_ban',
      title: '避开格点',
      subtitle: '总路径减经过',
      level: KnowledgeLevel.l4,
      prerequisites: ['lattice_path'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'circle_color',
      title: '环形染色',
      subtitle: '首尾也相邻',
      level: KnowledgeLevel.l5,
      prerequisites: ['adj_color'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'subset_ne',
      title: '非空子集',
      subtitle: r'$2^n-1$',
      level: KnowledgeLevel.l2,
      prerequisites: ['count_mul'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'hockey',
      title: '杨辉邻项',
      subtitle: r'$C(n,k)+C(n,k+1)$',
      level: KnowledgeLevel.l3,
      prerequisites: ['binom_identity'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'at_least',
      title: '至少选几个',
      subtitle: r'$\sum_{i\ge k}C(n,i)$',
      level: KnowledgeLevel.l4,
      prerequisites: ['combination'],
      practiceReady: true,
    ),
  ],
);
