import 'models.dart';

const kGeometryRootId = 'angle_basic';

/// Geometry tree: elementary measure through junior-high triangles.
final geometryGraph = KnowledgeGraph(
  area: KnowledgeArea.geometry,
  rootId: kGeometryRootId,
  nodes: const [
    KnowledgeNode(
      id: 'angle_basic',
      title: '角的计算',
      subtitle: '余角补角',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'perimeter',
      title: '周长',
      subtitle: '长方形与正方形',
      level: KnowledgeLevel.l1,
      prerequisites: ['angle_basic'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'rect_area',
      title: '长方形面积',
      subtitle: r'$ab$',
      level: KnowledgeLevel.l1,
      prerequisites: ['perimeter'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'triangle_area',
      title: '三角形面积',
      subtitle: r'$\frac{1}{2}ah$',
      level: KnowledgeLevel.l2,
      prerequisites: ['rect_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'trap_area',
      title: '梯形面积',
      subtitle: r'$\frac{(a+b)h}{2}$',
      level: KnowledgeLevel.l2,
      prerequisites: ['triangle_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'circle_measure',
      title: '圆的度量',
      subtitle: r'周长与面积',
      level: KnowledgeLevel.l2,
      prerequisites: ['rect_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cut_fill',
      title: '割补面积',
      subtitle: '大减小',
      level: KnowledgeLevel.l2,
      prerequisites: ['rect_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'parallel_angle',
      title: '平行线角',
      subtitle: '同位内错',
      level: KnowledgeLevel.l3,
      prerequisites: ['angle_basic'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'triangle_angle',
      title: '三角形内角',
      subtitle: r'内角和 $180^\circ$',
      level: KnowledgeLevel.l3,
      prerequisites: ['angle_basic'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'triangle_ineq',
      title: '三边关系',
      subtitle: '两边之和大于第三边',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'pythagorean',
      title: '勾股定理',
      subtitle: r'$a^2+b^2=c^2$',
      level: KnowledgeLevel.l4,
      prerequisites: ['triangle_ineq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'similar_tri',
      title: '相似三角形',
      subtitle: '对应边成比例',
      level: KnowledgeLevel.l4,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'box_volume',
      title: '长方体体积',
      subtitle: r'$abh$',
      level: KnowledgeLevel.l5,
      prerequisites: ['rect_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'surface_box',
      title: '长方体表面积',
      subtitle: r'$2(ab+ah+bh)$',
      level: KnowledgeLevel.l5,
      prerequisites: ['box_volume'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'circle_angle',
      title: '圆周角',
      subtitle: '圆心角与圆周角',
      level: KnowledgeLevel.l5,
      prerequisites: ['circle_measure', 'triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'solid_adv',
      title: '圆柱圆锥',
      subtitle: '体积与侧面积',
      level: KnowledgeLevel.l6,
      prerequisites: ['box_volume', 'circle_measure'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'poly_angle',
      title: '多边形内角',
      subtitle: r'$(n-2)180^\circ$',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sector_arc',
      title: '扇形弧长',
      subtitle: '圆心角占圆周',
      level: KnowledgeLevel.l4,
      prerequisites: ['circle_measure'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'symmetry',
      title: '轴对称',
      subtitle: '对称点坐标',
      level: KnowledgeLevel.l4,
      prerequisites: ['angle_basic'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'net_solid',
      title: '展开图',
      subtitle: '表面积摊平',
      level: KnowledgeLevel.l5,
      prerequisites: ['surface_box'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'reflect_path',
      title: '镜面最短路',
      subtitle: '展开成直线',
      level: KnowledgeLevel.l6,
      prerequisites: ['pythagorean'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sphere_vol',
      title: '球的度量',
      subtitle: r'$\frac{4}{3}\pi r^3$',
      level: KnowledgeLevel.l6,
      prerequisites: ['solid_adv'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'midline',
      title: '中位线',
      subtitle: '三角形与梯形',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_area', 'trap_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cong_tri',
      title: '全等三角形',
      subtitle: '对应边对应角',
      level: KnowledgeLevel.l4,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'area_ratio',
      title: '面积比',
      subtitle: '相似比的平方',
      level: KnowledgeLevel.l4,
      prerequisites: ['similar_tri'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'tangent_len',
      title: '切线长',
      subtitle: '圆外一点切线相等',
      level: KnowledgeLevel.l5,
      prerequisites: ['circle_measure', 'triangle_ineq'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cyclic_quad',
      title: '圆内接四边形',
      subtitle: r'对角互补',
      level: KnowledgeLevel.l5,
      prerequisites: ['circle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cone_slant',
      title: '圆锥展开',
      subtitle: '母线与扇形',
      level: KnowledgeLevel.l6,
      prerequisites: ['solid_adv', 'pythagorean'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'altitude',
      title: '等高面积',
      subtitle: '面积比等于底比',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_area'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'intercept',
      title: '平行截线',
      subtitle: '分线段成比例',
      level: KnowledgeLevel.l4,
      prerequisites: ['similar_tri', 'parallel_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'bisector',
      title: '角平分线',
      subtitle: '邻边比等于对段比',
      level: KnowledgeLevel.l4,
      prerequisites: ['similar_tri', 'triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'same_arc',
      title: '同弧圆周角',
      subtitle: '同弧所对相等',
      level: KnowledgeLevel.l5,
      prerequisites: ['circle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'ext_quad',
      title: '圆外切四边形',
      subtitle: '对边和相等',
      level: KnowledgeLevel.l5,
      prerequisites: ['tangent_len'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'power_pt',
      title: '圆幂',
      subtitle: '相交弦与切割线',
      level: KnowledgeLevel.l6,
      prerequisites: ['circle_measure', 'similar_tri'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'ext_angle',
      title: '三角形外角',
      subtitle: '等于不相邻内角和',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'iso_base',
      title: '等腰底角',
      subtitle: '两底角相等',
      level: KnowledgeLevel.l3,
      prerequisites: ['triangle_angle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'thales',
      title: '直径直角',
      subtitle: r'半圆上的圆周角 $90^\circ$',
      level: KnowledgeLevel.l5,
      prerequisites: ['circle_angle', 'pythagorean'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cyclic_out',
      title: '四点共圆外角',
      subtitle: '外角等于内对角',
      level: KnowledgeLevel.l5,
      prerequisites: ['cyclic_quad'],
      practiceReady: true,
    ),
  ],
);
