import 'models.dart';

const kRootNodeId = 'divisibility_def';

/// Canonical 20-node number-theory tree. L1–L3 are practice-ready.
final knowledgeGraph = KnowledgeGraph(
  rootId: kRootNodeId,
  nodes: const [
    KnowledgeNode(
      id: 'divisibility_def',
      title: '整除定义',
      subtitle: 'a|b 与因数',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'division_algorithm',
      title: '带余除法',
      subtitle: 'a = bq + r',
      level: KnowledgeLevel.l1,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'divisibility_rules',
      title: '整除特征',
      subtitle: '2/3/5/9/11',
      level: KnowledgeLevel.l1,
      prerequisites: ['division_algorithm'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'primes_composites',
      title: '质数与合数',
      subtitle: '素性判定',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'fta',
      title: '算术基本定理',
      subtitle: '质因数分解',
      level: KnowledgeLevel.l2,
      prerequisites: ['primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sieve',
      title: '埃氏筛法',
      subtitle: '筛出质数',
      level: KnowledgeLevel.l2,
      prerequisites: ['primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'gcd',
      title: '最大公约数',
      subtitle: 'GCD / 欧几里得',
      level: KnowledgeLevel.l3,
      prerequisites: ['division_algorithm', 'primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'lcm',
      title: '最小公倍数',
      subtitle: 'LCM 与恒等式',
      level: KnowledgeLevel.l3,
      prerequisites: ['gcd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'coprime',
      title: '互质',
      subtitle: 'gcd = 1',
      level: KnowledgeLevel.l3,
      prerequisites: ['gcd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'congruence_def',
      title: '同余定义',
      subtitle: 'a ≡ b (mod m)',
      level: KnowledgeLevel.l4,
      prerequisites: ['divisibility_def', 'division_algorithm'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'congruence_ops',
      title: '同余运算',
      subtitle: '加减乘等价',
      level: KnowledgeLevel.l4,
      prerequisites: ['congruence_def'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'complete_residue',
      title: '完全剩余系',
      subtitle: '模 m 代表元',
      level: KnowledgeLevel.l4,
      prerequisites: ['congruence_def'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'bezout',
      title: '裴蜀定理',
      subtitle: 'ax + by = gcd',
      level: KnowledgeLevel.l4,
      prerequisites: ['gcd', 'congruence_def'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'fermat',
      title: '费马小定理',
      subtitle: 'a^{p-1} ≡ 1',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'primes_composites'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'wilson',
      title: '威尔逊定理',
      subtitle: '(p-1)! ≡ -1',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'primes_composites'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'euler',
      title: '欧拉定理',
      subtitle: 'φ(n) 与幂剩余',
      level: KnowledgeLevel.l5,
      prerequisites: ['fermat', 'coprime'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'crt',
      title: '中国剩余定理',
      subtitle: '同余方程组',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'coprime'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'gauss_floor',
      title: '高斯函数',
      subtitle: '[x] 取整',
      level: KnowledgeLevel.l6,
      prerequisites: ['division_algorithm'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'diophantine',
      title: '不定方程',
      subtitle: '线性与高次',
      level: KnowledgeLevel.l6,
      prerequisites: ['bezout'],
      practiceReady: false,
    ),
    KnowledgeNode(
      id: 'base_binomial',
      title: '进位制与组合数',
      subtitle: '整除与进位',
      level: KnowledgeLevel.l6,
      prerequisites: ['fta', 'divisibility_rules'],
      practiceReady: false,
    ),
  ],
);
