import 'models.dart';

export 'algebra_graph.dart';
export 'calculation_graph.dart';
export 'combinatorics_graph.dart';
export 'geometry_graph.dart';
export 'logic_graph.dart';

const kRootNodeId = 'divisibility_def';

/// Number theory tree. All six levels are practice-ready.
final knowledgeGraph = KnowledgeGraph(
  area: KnowledgeArea.numberTheory,
  rootId: kRootNodeId,
  nodes: const [
    KnowledgeNode(
      id: 'divisibility_def',
      title: '整除定义',
      subtitle: r'$a \mid b$ 与因数',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'division_algorithm',
      title: '带余除法',
      subtitle: r'$a = bq + r$',
      level: KnowledgeLevel.l1,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'divisibility_rules',
      title: '整除特征',
      subtitle: '2/3/5/9/11',
      level: KnowledgeLevel.l1,
      prerequisites: ['division_algorithm'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'primes_composites',
      title: '质数与合数',
      subtitle: '素性判定',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'fta',
      title: '算术基本定理',
      subtitle: '质因数分解',
      level: KnowledgeLevel.l2,
      prerequisites: ['primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'sieve',
      title: '埃氏筛法',
      subtitle: '筛出质数',
      level: KnowledgeLevel.l2,
      prerequisites: ['primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'perfect_square',
      title: '完全平方',
      subtitle: r'$n=k^2$',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'square_end',
      title: '平方个位',
      subtitle: '0,1,4,5,6,9',
      level: KnowledgeLevel.l2,
      prerequisites: ['perfect_square'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'gcd',
      title: '最大公约数',
      subtitle: 'GCD / 欧几里得',
      level: KnowledgeLevel.l3,
      prerequisites: ['division_algorithm', 'primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'lcm',
      title: '最小公倍数',
      subtitle: 'LCM 与恒等式',
      level: KnowledgeLevel.l3,
      prerequisites: ['gcd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'coprime',
      title: '互质',
      subtitle: r'$\gcd(a, b) = 1$',
      level: KnowledgeLevel.l3,
      prerequisites: ['gcd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'congruence_def',
      title: '同余定义',
      subtitle: r'$a \equiv b \pmod{m}$',
      level: KnowledgeLevel.l4,
      prerequisites: ['divisibility_def', 'division_algorithm'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'congruence_ops',
      title: '同余运算',
      subtitle: '加减乘等价',
      level: KnowledgeLevel.l4,
      prerequisites: ['congruence_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'complete_residue',
      title: '完全剩余系',
      subtitle: r'模 $m$ 代表元',
      level: KnowledgeLevel.l4,
      prerequisites: ['congruence_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'bezout',
      title: '裴蜀定理',
      subtitle: r'$ax + by = \gcd(a, b)$',
      level: KnowledgeLevel.l4,
      prerequisites: ['gcd', 'congruence_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'fermat',
      title: '费马小定理',
      subtitle: r'$a^{p-1} \equiv 1 \pmod{p}$',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'wilson',
      title: '威尔逊定理',
      subtitle: r'$(p-1)! \equiv -1 \pmod{p}$',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'primes_composites'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'euler',
      title: '欧拉定理',
      subtitle: r'$\varphi(n)$ 与幂剩余',
      level: KnowledgeLevel.l5,
      prerequisites: ['fermat', 'coprime'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'crt',
      title: '中国剩余定理',
      subtitle: '同余方程组',
      level: KnowledgeLevel.l5,
      prerequisites: ['congruence_ops', 'coprime'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'gauss_floor',
      title: '高斯函数',
      subtitle: r'$[x]$ 取整',
      level: KnowledgeLevel.l6,
      prerequisites: ['division_algorithm'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'diophantine',
      title: '不定方程',
      subtitle: '线性与高次',
      level: KnowledgeLevel.l6,
      prerequisites: ['bezout'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'base_binomial',
      title: '进位制与组合数',
      subtitle: '整除与进位',
      level: KnowledgeLevel.l6,
      prerequisites: ['fta', 'divisibility_rules'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'power_last',
      title: '幂的末位',
      subtitle: '个位循环节',
      level: KnowledgeLevel.l6,
      prerequisites: ['divisibility_rules', 'congruence_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'count_mult',
      title: '倍数个数',
      subtitle: r'$\lfloor n/d\rfloor$',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'digit_root',
      title: '数根',
      subtitle: '反复数字和',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_rules'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'divisor_sum',
      title: '因数和',
      subtitle: r'$\sigma(n)$',
      level: KnowledgeLevel.l3,
      prerequisites: ['fta'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'odd_div',
      title: '奇数因数',
      subtitle: '先除掉 2',
      level: KnowledgeLevel.l3,
      prerequisites: ['fta'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'last_two',
      title: '幂的末两位',
      subtitle: r'$a^n \bmod 100$',
      level: KnowledgeLevel.l6,
      prerequisites: ['power_last'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'near_div',
      title: '邻近倍数',
      subtitle: '大于 n 的最小倍数',
      level: KnowledgeLevel.l2,
      prerequisites: ['divisibility_def'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'base_ops',
      title: '进制加减',
      subtitle: '先化十进制',
      level: KnowledgeLevel.l3,
      prerequisites: ['division_algorithm'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cycle_len',
      title: '分数循环节',
      subtitle: r'$1/n$ 的周期',
      level: KnowledgeLevel.l6,
      prerequisites: ['congruence_ops', 'divisibility_rules'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'base_mul',
      title: '进制乘法',
      subtitle: '化十进制再乘',
      level: KnowledgeLevel.l5,
      prerequisites: ['base_ops'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'repunit',
      title: '单位重复数',
      subtitle: r'$R_n=11\ldots 1$',
      level: KnowledgeLevel.l5,
      prerequisites: ['divisibility_rules'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'fact_zero',
      title: '阶乘末零',
      subtitle: r'$n!$ 尾零',
      level: KnowledgeLevel.l6,
      prerequisites: ['base_binomial', 'gauss_floor'],
      practiceReady: true,
    ),
  ],
);
