import 'models.dart';

const kLogicRootId = 'even_odd';

/// Logic tree: parity, truth, reconstruction, and simple invariants.
final logicGraph = KnowledgeGraph(
  area: KnowledgeArea.logic,
  rootId: kLogicRootId,
  nodes: const [
    KnowledgeNode(
      id: 'even_odd',
      title: '奇偶分析',
      subtitle: '和差积的奇偶',
      level: KnowledgeLevel.l1,
      prerequisites: [],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'true_count',
      title: '真假判断',
      subtitle: '恰有几句为真',
      level: KnowledgeLevel.l1,
      prerequisites: ['even_odd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'digit_riddle',
      title: '数字谜',
      subtitle: '还原各位数字',
      level: KnowledgeLevel.l2,
      prerequisites: ['even_odd'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'undo_op',
      title: '逆推还原',
      subtitle: '从结果往回算',
      level: KnowledgeLevel.l2,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'max_min',
      title: '最大最小',
      subtitle: '数位与和约束',
      level: KnowledgeLevel.l2,
      prerequisites: ['digit_riddle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'weigh_count',
      title: '天平次数',
      subtitle: r'$3^n$ 分堆',
      level: KnowledgeLevel.l3,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'weekday',
      title: '星期循环',
      subtitle: '模 7',
      level: KnowledgeLevel.l3,
      prerequisites: ['undo_op'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'clock_hand',
      title: '钟面夹角',
      subtitle: '时针与分针',
      level: KnowledgeLevel.l3,
      prerequisites: ['max_min'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'remainder_cycle',
      title: '周期报数',
      subtitle: '围圈与余数',
      level: KnowledgeLevel.l4,
      prerequisites: ['weekday'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'invariant_parity',
      title: '奇偶不变',
      subtitle: '操作不改变的量',
      level: KnowledgeLevel.l4,
      prerequisites: ['even_odd', 'weigh_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'nim_take',
      title: '取石子',
      subtitle: '减法博弈',
      level: KnowledgeLevel.l5,
      prerequisites: ['remainder_cycle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'schedule',
      title: '统筹安排',
      subtitle: '两人分三事',
      level: KnowledgeLevel.l5,
      prerequisites: ['undo_op'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'queue_wait',
      title: '排队等候',
      subtitle: '人数乘时间',
      level: KnowledgeLevel.l5,
      prerequisites: ['max_min'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'cut_rope',
      title: '锯绳计数',
      subtitle: '段数与刀数',
      level: KnowledgeLevel.l6,
      prerequisites: ['invariant_parity'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'load_pack',
      title: '装载最省',
      subtitle: '容量整除',
      level: KnowledgeLevel.l6,
      prerequisites: ['max_min'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'who_map',
      title: '谁是谁',
      subtitle: '对应与排除',
      level: KnowledgeLevel.l2,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'liar_pair',
      title: '一真一假',
      subtitle: '恰好一句为真',
      level: KnowledgeLevel.l3,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'match_count',
      title: '比赛场次',
      subtitle: '循环与淘汰',
      level: KnowledgeLevel.l3,
      prerequisites: ['max_min'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'crossing',
      title: '过河次数',
      subtitle: '船载二人',
      level: KnowledgeLevel.l4,
      prerequisites: ['undo_op'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'seating',
      title: '围坐对位',
      subtitle: '圆桌编号',
      level: KnowledgeLevel.l4,
      prerequisites: ['remainder_cycle'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'weigh_fake',
      title: '找假币',
      subtitle: '天平分堆',
      level: KnowledgeLevel.l5,
      prerequisites: ['weigh_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'box_label',
      title: '标签全错',
      subtitle: '三盒必错标',
      level: KnowledgeLevel.l3,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'who_story',
      title: '排名对应',
      subtitle: '高矮与名次',
      level: KnowledgeLevel.l4,
      prerequisites: ['who_map'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'hat_logic',
      title: '帽子推理',
      subtitle: '看见同色则异色',
      level: KnowledgeLevel.l4,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'wolf_goat',
      title: '狼羊过河',
      subtitle: '互斥与摆渡',
      level: KnowledgeLevel.l5,
      prerequisites: ['crossing'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'three_say',
      title: '三人发言',
      subtitle: '恰一句为真',
      level: KnowledgeLevel.l3,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'order_true',
      title: '恰好几句真',
      subtitle: '自指命题',
      level: KnowledgeLevel.l3,
      prerequisites: ['true_count'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'who_chain',
      title: '四人排名',
      subtitle: '排除定名次',
      level: KnowledgeLevel.l4,
      prerequisites: ['who_story'],
      practiceReady: true,
    ),
    KnowledgeNode(
      id: 'light_sq',
      title: '开关灯',
      subtitle: '完全平方亮着',
      level: KnowledgeLevel.l4,
      prerequisites: ['even_odd'],
      practiceReady: true,
    ),
  ],
);
